--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XGDavid/XGTSmithingTable
build-by-default: true
branches:
- main
projects:
  XGTSmithingTable:
    path: ""
    icon: "logo.png"
...
